---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.6.3
    container_name: heimdall
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "{{ containerd.container_root }}/{{ service }}/data:/config"
    ports:
      - "{{ containerd.services_conf.heimdall.port }}:443"
    restart: unless-stopped