services:
  linkstack:
    image: linkstackorg/linkstack:4.8.4
    environment:
      - TZ=America/chicago
      - SERVER_ADMIN=admin@example.xyz
      - HTTP_SERVER_NAME={{ containerd.services_conf.linkstack.domain }}
      - HTTPS_SERVER_NAME={{ containerd.services_conf.linkstack.domain }}
      - LOG_LEVEL=info
      - PHP_MEMORY_LIMIT=512M
      - UPLOAD_MAX_FILESIZE=256M
    ports:
      - "{{ containerd.services_conf.linkstack.port }}:443"
    volumes:
      - linkstack:/htdocs
    restart: unless-stopped
volumes:
  linkstack: