---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.3.2 
    container_name: mealie
    ports:
      - "{{ containerd.services_conf.mealie.port }}:9000"
    deploy:
      resources:
        limits:
          memory: 1024M
    volumes:
      - "{{ containerd.container_root }}/{{ service }}/data:/app/data/"
    environment:
      # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://{{ containerd.services_conf.mealie.domain }}
      - TOKEN_TIME=800
      - SECURITY_USER_LOCKOUT_TIME=1
    restart: unless-stopped