---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.2.0 
    container_name: mealie
    ports:
      - "{{ containerd.services_conf.mealie.port }}:9000"
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - "{{ containerd.container_root }}/{{ service }}/data:/app/data/"
    environment:
      # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://{{ containerd.services_conf.mealie.domain }}
    restart: unless-stopped