---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - "{{ containerd.container_root }}/{{ service }}/data:/app/data"
    ports:
      - "{{ containerd['services_conf']['uptime-kuma']['port'] }}:3001"
    restart: unless-stopped